apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gizmosql-mcp.fullname" . }}
  labels:
    {{- include "gizmosql-mcp.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{- if ne (toString $value) "" }}
  {{ $key }}: {{ toString $value | quote }}
  {{- end }}
  {{- end }}
