{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gizmosql-mcp.fullname" . }}
  labels:
    {{- include "gizmosql-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{- if ne (toString $value) "" }}
  {{ $key }}: {{ toString $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
